APPDIR=../../../../..
SRCDIR=$(APPDIR)/src/main
RESDIR=$(SRCDIR)/res

install:
	cp build.gradle $(APPDIR)
	cp AndroidManifest.xml $(SRCDIR)
	cp res/mipmap-hdpi/* $(RESDIR)/mipmap-hdpi
	cp res/mipmap-mdpi/* $(RESDIR)/mipmap-mdpi
	cp res/mipmap-xhdpi/* $(RESDIR)/mipmap-xhdpi
	cp res/mipmap-xxhdpi/* $(RESDIR)/mipmap-xxhdpi
	cp res/mipmap-xxxhdpi/* $(RESDIR)/mipmap-xxxhdpi
