name: "🛠 Contribution task"
description: "Define a task that anyone can pick up to help the project."
title: "[TASK]"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        This template is for defining actionable tasks that can be implemented or experimented on.

  - type: input
    id: task
    attributes:
      label: "Task title"
      description: "Short title describing the task"
      placeholder: "Implement spoken language demo…"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Detailed description"
      description: "What needs to be done / expectations / hints"
      placeholder: "Step-by-step or outcome"

  - type: dropdown
    id: skill
    attributes:
      label: "Skill area"
      options:
        - "C/C++"
        - "Build / Docs"
        - "Integration / Plugin"
        - "Experiment / benchmark"
      default: "C/C++"

  - type: dropdown
    id: difficulty
    attributes:
      label: "Estimated difficulty"
      options:
        - "S"
        - "M"
        - "L"
      default: "M"

  - type: input
    id: reward
    attributes:
      label: "Recognition / output"
      description: "What recognition is given (paper mention, co-authorship, citation…) if applicable"
