/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109535-gfcd557a-Reino"
#endif /* AVUTIL_FFVERSION_H */
