name: MSBuild
on: [push]
jobs:
  build:
    name: MSBuild
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild /p:Configuration=Release MMDAgent_vs2022.sln

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-result
        path: |
          Release/MMDAgent-EX.exe
          Release/Plugins/
        
